GET http://localhost:8000/students

###

GET http://localhost:8000/students/6695513b03d7175f793cb1c0

###

POST http://localhost:8000/students
Content-Type: application/json

{
  "name": "Samuel Farmer",
  "class": "DWA"
}

###

PATCH http://localhost:8000/students/66955fda4f7b1f35697eaf44
Content-Type: application/json

{
  "name": "Samuel Farmer",
  "class": "DWA"
}

###


DELETE http://localhost:8000/students/66955fd54f7b1f35697eaf42