GET http://localhost:8000/students

###

GET http://localhost:8000/students/66955fda4f7b1f35697eaf44

###

POST http://localhost:8000/students
Content-Type: application/json

{
  "name": "Samuel Q Farmer",
  "class": "DWA"
}

###

PATCH http://localhost:8000/students/66957f242705eb999edaf044
Content-Type: application/json

{
  "name": "Samuel Farmer",
  "class": "DWA2"
}

###


DELETE http://localhost:8000/students/66957f242705eb999edaf044